model_list:
  - model_name: my-groq-model
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: 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

  - model_name: my-groq-fast
    litellm_params:
      model: groq/llama-3.1-8b-instant
      api_key: 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

general_settings:
  master_key: sk-myproxy-secret123
